import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Lexend } from 'next/font/google'

const lexend = Lexend({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Vocábulo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lexend.className} antialiased bg-blue-900`}
      >
        {children}
      </body>
    </html>
  );
}
